### ISSUE TITLE
create a README.md file with instructions to compile and run

### ISSUE THREAD

**Issue by melvinzhang** [nginyc/Magnets#1]

**Comment by melvinzhang** [comment]
I manage to get it working with the gradlew script after setting ANDROID_HOME to point to the folder with the SDK. 

However, running `./gradlew desktop:run` fails with the following error
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: Graphics/Floor/Floor 1.png
        at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148)
        at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
        at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
        at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:96)
        at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:84)
        at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:65)
        at com.somethingyellow.magnets.PlayScreen.loadLevel(PlayScreen.java:137)
        at com.somethingyellow.magnets.PlayScreen.show(PlayScreen.java:130)
        at com.badlogic.gdx.Game.setScreen(Game.java:61)
        at com.somethingyellow.magnets.Main.create(Main.java:10)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: Graphics/Floor/Floor 1.png (Internal)
        at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
        at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:222)
        at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:145)
        ... 11 more
```

**Comment by nginyc** [comment]
Hi Melvin,

Please check out the latest set of code - that was because the .tmx files were not configured properly.
Anyway, are you able to explain how did you use the gradlew script in the command line? I'm not too sure how to compile & run the program outside of Android Studio :grin:

**Comment by melvinzhang** [comment]
I just tried it based on b3307305ab4, the error now is
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.SerializationException: Error parsing file: Levels/Triparte.tmx
        at com.badlogic.gdx.utils.XmlReader.parse(XmlReader.java:83)
        at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:78)
        at com.badlogic.gdx.maps.tiled.TmxMapLoader.load(TmxMapLoader.java:65)
        at com.somethingyellow.magnets.PlayScreen.loadLevel(PlayScreen.java:121)
        at com.somethingyellow.magnets.PlayScreen.show(PlayScreen.java:114)
        at com.badlogic.gdx.Game.setScreen(Game.java:61)
        at com.somethingyellow.magnets.Main.create(Main.java:10)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: Levels/Triparte.tmx (Internal)
        at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:136)
        at com.badlogic.gdx.files.FileHandle.reader(FileHandle.java:163)
        at com.badlogic.gdx.utils.XmlReader.parse(XmlReader.java:81)
```
Looks like the file Triparte.tmx is missing from the repo

**Comment by melvinzhang** [comment]
For the gradlew script, I read up the libgdx docs at https://github.com/libgdx/libgdx/wiki/Gradle-on-the-Commandline#running-the-desktop-project

Provided `ANDROID_HOME` is setup to point to the Androi SDK, `gradlew desktop:run` starts the desktop app. Currently it is working and I'm able to load the level where you have to build a chain of blocks link the source to the block in front of the exit.

**Comment by nginyc** [comment]
Haha sorry for all the errors - they were arising because of some miscoordination between the .tmx files and the code. The current iteration (`5005b23`) should be working, if not try the previous few.

Anyway, not all the puzzles available now are solvable because of some change in the game mechanics. You'll be able to change which .tmx file and puzzle is loaded by changing the value of `_levelPath` in `PlayScreen.java` in package `com.somethingyellow.magnets`.

Tell us if there is anything we can improve about our project organisation, and thanks for your explanation about gradlew script! I'll take some time soon to write up on the readme on how to compile and run

**Comment by melvinzhang** [comment]
I can confirm that 5005b23 is working for me, running `gradlew desktop:run` automatically installs gradle and dependencies and then compiles and start the desktop app.

**Comment by nginyc** [comment]
I have updated the readme with instructions on how to compile and run - is it clear enough and sufficient?

**Comment by melvinzhang** [comment]
I think it is missing the requirement on the JDK, otherwise it looks pretty good.

**Comment by nginyc** [comment]
Added more details to the readme, hopefully its clearer

**Comment by melvinzhang** [comment]
Much nicer now!
